version: '2.2'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  serverless:
    build:
      dockerfile: serverless.Dockerfile
      context: .
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
  ruby:
    build:
      context: .
      args:
        ENVIRONMENT: test
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
    entrypoint: sh
    command:
      - "-c"
      - "not meant to be run with the stack"
  unit:
    extends: ruby
    entrypoint: rspec
    environment:
      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
    command:
      - --tag
      - unit
      - --fail-fast
      - --format
      - documentation
  integration-setup:
    extends: serverless
    entrypoint: bash
    command:
      - -c
      - ./scripts/integration_setup.sh
  integration-teardown:
    extends: serverless
    command:
      - remove
      - --stage
      - develop
  integration:
    extends: ruby
    entrypoint: rspec
    env_file: .env
    environment:
      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - "$PWD/secrets:/secrets"
    command:
      - --tag
      - integration
      - --fail-fast
      - --format
      - documentation

