version: '3.7'
services:
  serverless:
    env_file: .env
    working_dir: /app
    build:
      dockerfile: serverless.Dockerfile
      context: .
  vendor:
    env_file: .env
    volumes:
      - $PWD/vendor:/vendor
    build:
      dockerfile: app.Dockerfile
      context: .
    command:
      - sh
      - -c
      - "go mod vendor && go install && cp -R ./vendor/* /vendor"
  local-flightaware:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - $PWD/test/fixtures:/etc/nginx/html:ro
      - $PWD/test/nginx.conf:/etc/nginx/nginx.conf:ro
  unit:
    env_file: .env
    environment:
      LOG_LEVEL: $LOG_LEVEL
    build:
      dockerfile: app.Dockerfile
      context: .
    volumes:
      - $PWD:/go/github.com/carlosonunez/flightaware-bot/src
    entrypoint:
      - go
      - test
      - -tags=unit
  local_e2e:
    env_file: .env
    environment:
      LOG_LEVEL: $LOG_LEVEL
      FLIGHTAWARE_BASE_URL: "http://local-flightaware"
    build:
      dockerfile: app.Dockerfile
      context: .
      args:
        INCLUDE_E2E: "true"
    volumes:
      - $PWD:/go/github.com/carlosonunez/flightaware-bot/src
    entrypoint:
      - go
      - test
      - -tags=local_e2e
  integration-setup:
    extends: serverless
    entrypoint: bash
    command:
      - -c
      - ./scripts/integration_setup.sh
  integration-teardown:
    extends: serverless
    command:
      - remove
      - --stage
      - develop
  integration:
    env_file: .env
    build:
      dockerfile: app.Dockerfile
      context: .
    command:
      - go
      - test
      - -tags=integration
