version: '3.7'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  serverless:
    env_file: .env
    working_dir: /app
    build:
      dockerfile: serverless.Dockerfile
      context: .
  vendor:
    env_file: .env
    volumes:
      - $PWD/vendor:/vendor
    build:
      dockerfile: app.Dockerfile
      context: .
    command:
      - sh
      - -c
      - "go mod vendor && go install && cp -R ./vendor/* /vendor"
  unit:
    env_file: .env
    environment:
      SELENIUM_HUB_URL: http://selenium:4444/wd/hub
    build:
      dockerfile: app.Dockerfile
      context: .
    command:
      - go
      - test
  integration-setup:
    extends: serverless
    entrypoint: bash
    command:
      - -c
      - ./scripts/integration_setup.sh
  integration-teardown:
    extends: serverless
    command:
      - remove
      - --stage
      - develop
  integration:
    env_file: .env
    build:
      dockerfile: app.Dockerfile
      context: .
    command:
      - go
      - test
      - -tags=integration
