---
plugins: ${file(./serverless_plugins.yml):${self:provider.stage}}

service:
  name: flightaware-flight-info

frameworkVersion: '>=1.0.0'

provider:
  name: aws
  runtime: ruby2.5
  region: ${env:AWS_REGION, 'us-east-2'}
  memorySize: 256
  deploymentBucket:
    name: ${env:SERVERLESS_BUCKET_NAME}
  deploymentPrefix: serverless
  apiKeys:
    - default_key
  tracing:
    apiGateway: true

package:
  include:
    - lib/**
    - bin/**
    - vendor/**
  exclude:
    - scripts/**
    - secrets/**
    - infra/**
    - docker-compose.*
    - .terraform/**
    - spec/**
    - .env*

functions:
  flight_info:
    handler: lib/flight-info.get
    description: Gets flight information when given a flight number.
    timeout: 30
    environment:
      GEM_PATH: vendor/bundle
    events:
      - http:
          path: get_flight_info
          method: get
          private: true

custom:
  stage: "${opt:stage, self:provider.stage}"
  production:
    customDomain:
      domainName: ${env:DOMAIN_PATH}.${env:DOMAIN_TLD}
      basePath: ''
      createRoute53Record: true
