---
plugins:
  - serverless-domain-manager
  - serverless-plugin-warmup

service:
  name: flightaware-flight-info

frameworkVersion: '>=1.0.0'

provider:
  name: aws
  runtime: ruby2.7
  architecture: "${self:custom.architecture}"
  region: ${env:AWS_REGION, 'us-east-2'}
  deploymentBucket:
    name: ${env:SERVERLESS_BUCKET_NAME}-${env:ENVIRONMENT}
  deploymentPrefix: serverless
  apiKeys:
    - default_key_${env:ENVIRONMENT}
  tracing:
    apiGateway: true
  environment:
    PROXY_HOST: ${env:PROXY_HOST}
    PROXY_PORT: ${env:PROXY_PORT}
    TAILSCALE_AUTH_KEY: ${env:TAILSCALE_AUTH_KEY}
    TAILSCALE_EXIT_NODE_IP: ${env:TAILSCALE_EXIT_NODE_IP}
    TS_TEST_URL: ${env:TS_TEST_URL}
    TS_TEST_WANT: ${env:TS_TEST_WANT}
  ecr:
    images:
      app:
        path: .
        platform: "linux/${self:custom.architecture}"

package:
  include:
    - lib/**
    - bin/**
    - vendor/**
  exclude:
    - include/**
    - scripts/**
    - secrets/**
    - infra/**
    - docker-compose.*
    - .terraform/**
    - spec/**
    - .env*

functions:
  ping:
    memorySize: 128
    image:
      name: app
      command: bin/flight-info.get_ping
    events:
      - http:
          path: ping
          method: get
    warmup:
      default:
        enable: false
  chromium_ping:
    memorySize: 512
    timeout: 30
    image:
      name: app
      command: bin/flight-info.test_chromium_launch
    events:
      - http:
          path: debugChromium
          method: get
          private: true
    warmup:
      default:
        enable: true
  test_internet_access:
    memorySize: 512
    timeout: 30
    image:
      name: app
      command: bin/flight-info.test_internet_access
    events:
      - http:
          path: testInternetAccess
          method: get
          private: true
    warmup:
      default:
        enable: true
  flight_info:
    timeout: 30
    # Make more room for static assets that FlightAware loads
    memorySize: 1024
    image:
      name: app
      command: bin/flight-info.get_flight_info
    events:
      - http:
          path: flightInfo
          method: get
          private: true
    warmup:
      default:
        enable: true

custom:
  architecture: arm64
  enableCustomDomain:
    develop: false
    v1: true
  warmup:
    default:
      enabled: true
      memorySize: 512
      verbose: true
  customDomain:
    stage: v1
    domainName: ${env:DOMAIN_PATH}.${env:DOMAIN_TLD}
    certificateArn: ${file(./secrets/certificate_arn)}
    basePath: 'v1'
    createRoute53Record: true
    enabled: ${self:custom.enableCustomDomain.${opt:stage, self:provider.stage}}
