---
plugins:
  - serverless-domain-manager

service:
  name: flightaware-flight-info

frameworkVersion: '>=1.0.0'

layers:
  firefox:
    package:
      artifact: layers/firefox.zip

provider:
  name: aws
  runtime: go1.x
  region: ${env:AWS_REGION, 'us-east-2'}
  memorySize: 1024
  deploymentBucket:
    name: ${env:SERVERLESS_BUCKET_NAME}-${env:SERVERLESS_ENVIRONMENT}
  deploymentPrefix: serverless
  apiKeys:
    - ${self:custom.keyName.${opt:stage, self:provider.stage}}
  tracing:
    apiGateway: true

package:
  exclude:
    - ./**
  include:
    - bin/**

functions:
  ping:
    handler: bin/healthcheck
    description: Tests that flight info bot is up and running.
    timeout: 30
    events:
      - http:
          path: ping
          method: get

custom:
  keyName:
    develop: default-key-test
    v1: default-key-production
  enableCustomDomain:
    develop: false
    v1: true
  customDomain:
    stage: v1
    domainName: ${env:DOMAIN_PATH}.${env:DOMAIN_TLD}
    certificateArn: ${file(./secrets/certificate_arn)}
    basePath: 'v1'
    createRoute53Record: true
    enabled: ${self:custom.enableCustomDomain.${opt:stage, self:provider.stage}}
