---
name: Travel Update Bot Deployment
on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Docker Compose
        run: curl -L ${DOCKER_COMPOSE_URL}/docker-compose-`uname -s`-`uname -m` > ./docker-compose &&
             chmod +x ./docker-compose
        env:
          DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/1.22.0

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Run unit tests
        run: ./scripts/unit
        env:
          NO_VENDOR: 'true'

  integration_tests:
    needs: [unit_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Docker Compose
        run: curl -L ${DOCKER_COMPOSE_URL}/docker-compose-`uname -s`-`uname -m` > ./docker-compose &&
             chmod +x ./docker-compose
        env:
          DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/1.22.0

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Run integration tests
        run: ./scripts/integration
        env:
          NO_VENDOR: 'true'

      - name: Destroy integration environment
        run: ./scripts/destroy

  deploy_to_production:
    needs: [unit_tests, integration_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Docker Compose
        run: curl -L ${DOCKER_COMPOSE_URL}/docker-compose-`uname -s`-`uname -m` > ./docker-compose &&
             chmod +x ./docker-compose
        env:
          DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/1.22.0

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Deploy to Production
        run: ENVIRONMENT=production ./scripts/deploy
        env:
          NO_VENDOR: 'true'

      - name: Run smoke test
        run: ./scripts/ping_production
