---
name: Nightly integration test environment cleanup
on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  delete_outstanding_integration_environments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Docker Compose
        run: curl -L ${DOCKER_COMPOSE_URL}/docker-compose-`uname -s`-`uname -m` > ./docker-compose &&
             chmod +x ./docker-compose
        env:
          DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/v2.2.3

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Delete integration environment
        run: ./scripts/destroy
